# Generated by Django 3.2.7 on 2021-09-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_csvmaster_csvname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvmaster',
            name='CsvName',
            field=models.FileField(upload_to='G:/SIGITApi'),
        ),
    ]
